name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Demo LS on VPS
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd public_html/travaux/ 
          git clone git@github.com:MathieuLePuil/WR602D-Website.git
          cd WR602D-Website
          git pull
  
          echo 'DATABASE_URL="mysql://${{ secrets.BASEUSER }}:${{ secrets.BASEPASS }}@localhost:3306/${{ secrets.BASENAME }}?serverVersion=8.0.32&charset=utf8mb4"' >> .env
          echo "APP_ENV=prod" > .env.local

          npm install

          composer install
          composer upgrade
          php bin/console d:d:c
          php bin/console d:s:u -f
          php bin/console c:c
